### ISSUE TITLE
Add dependencies to readme.md

### ISSUE THREAD

**Issue by bthayer2365** [thomasdriscoll/open-source-illinois-web#12]
You say we use AngularCLI 7.3.8 and link the repo, but that doesn't really tell you how to install for general use.
These might be useful:
https://www.lucidchart.com/techblog/2016/12/12/installing-angular-2-and-other-dependencies/
https://angular.io/guide/setup-local

Here's what I did, but it still isn't quite working. I'll work with Brian to get this set up and then write it all down here again then make sure it works on my other computer.
1) install nodejs
a) using conda
 conda install -c conda-forge nodejs 
b) other???

3) install angular
npm install -g @angular/cli

4) init project
ng init

5) run
ng serve

**Comment by tdog191** [comment]
I have explored this, and the conclusion I came to is largely the same procedure.  The main difference is that I believe the third step should be to run "npm install" to install the project's dependencies.  Then the setup process works.

I started #15 to update the README for greater clarity.
